services:
  mysql:
    image: mysql:latest
    container_name: billwerk_mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    container_name: billwerk_wp
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    user: "1000:1000" # linux
    volumes:
      - ./wp_data:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini

      - ../reepay-woocommerce-payment:/var/www/html/wp-content/plugins/reepay-woocommerce-payment # plugin project
      - ../reepay-woocommerce-subscriptions:/var/www/html/wp-content/plugins/reepay-woocommerce-subscriptions # plugin project
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      XDEBUG_CONFIG: client_host=host.docker.internal

volumes:
  db_data:
